### ISSUE TITLE
Code is only for Windows.....

### ISSUE THREAD

**Issue by abixadamj** [salabim/simply_black#1]
Consider Linux or Mac as a platform....

```
import sys

if sys.platform is "linux" or "darwin":
    black_bin = "/usr/local/black" 
else:
    black_bin = "black.exe"
```

**Comment by salabim** [comment]
Thanks. I'll change the code accordingly.

/Ruud

**Comment by salabim** [comment]
Thanks. I'll change the code accordingly.

**Comment by abixadamj** [comment]
Of course for Linux should be:
```black_bin = "/usr/local/bin/black" ```

**Comment by salabim** [comment]
Changes applied. Not tested (yet).

**Comment by salabim** [comment]
Tested on Linux (Raspberry Pi)

**Comment by abixadamj** [comment]
In simply_black.py

```blackbin is not a black_bin``` 
So, there is sg.popup("black.exe not found...."
;-)

**Comment by abixadamj** [comment]
In simply_black.embedded.py:

```
adasiek@mint-desktop:~/python_projekty/simply_black$ python3 simply_black.embedded.py 
Traceback (most recent call last):
  File "simply_black.embedded.py", line 41, in <module>
    import MySimpleGUI as sg
  File "/tmp/embedded_MySimpleGUI/MySimpleGUI/__init__.py", line 1, in <module>
    from .MySimpleGUI import *
  File "/tmp/embedded_MySimpleGUI/MySimpleGUI/MySimpleGUI.py", line 648, in <module>
    + this_pysimplegui_version
NotImplementedError: MySimpleGUI requires PySimpleGUI >= 4.27.4, not 4.25.0
```

**Comment by abixadamj** [comment]
I have on my system:

```
adasiek@mint-desktop:~/python_projekty/simply_black$ pip3 list | grep Simple
MySimpleGUI            1.1.8
PySimpleGUI            4.29.0
```

**Comment by salabim** [comment]
simply_black now runs under Linux (tested).

**Comment by salabim** [comment]
> In simply_black.embedded.py:
> 
> ```
> adasiek@mint-desktop:~/python_projekty/simply_black$ python3 simply_black.embedded.py 
> Traceback (most recent call last):
>   File "simply_black.embedded.py", line 41, in <module>
>     import MySimpleGUI as sg
>   File "/tmp/embedded_MySimpleGUI/MySimpleGUI/__init__.py", line 1, in <module>
>     from .MySimpleGUI import *
>   File "/tmp/embedded_MySimpleGUI/MySimpleGUI/MySimpleGUI.py", line 648, in <module>
>     + this_pysimplegui_version
> NotImplementedError: MySimpleGUI requires PySimpleGUI >= 4.27.4, not 4.25.0
> ```

I am afraid you have a PySimpleGUI version 4.25.0 in the directory you are running simply_black from. Just remove that one and it should work.

**Comment by abixadamj** [comment]
simply_black runs OK on Linux ;-)

![Zrzut ekranu z 2020-10-07 13-28-56](https://user-images.githubusercontent.com/5088643/95325244-319c0f00-08a1-11eb-9a95-d4e53e029d26.png)

**Comment by abixadamj** [comment]
But with embedded there is still error - I have only files clone by git from your repo.

```
adasiek@mint-desktop:~/python_projekty/simply_black$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From github.com:salabim/simply_black
   2867a23..97ee2a2  master     -> origin/master
Updating 2867a23..97ee2a2
Fast-forward
 simply_black changelog.txt |   5 ++++
 simply_black.embedded.py   | 114 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------
 simply_black.py            | 114 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------
 3 files changed, 181 insertions(+), 52 deletions(-)
adasiek@mint-desktop:~/python_projekty/simply_black$ python3 simply_black.py 
adasiek@mint-desktop:~/python_projekty/simply_black$ python3 simply_black.embedded.py 
Traceback (most recent call last):
  File "simply_black.embedded.py", line 41, in <module>
    import MySimpleGUI as sg
  File "/tmp/embedded_MySimpleGUI/MySimpleGUI/__init__.py", line 1, in <module>
    from .MySimpleGUI import *
  File "/tmp/embedded_MySimpleGUI/MySimpleGUI/MySimpleGUI.py", line 648, in <module>
    + this_pysimplegui_version
NotImplementedError: MySimpleGUI requires PySimpleGUI >= 4.27.4, not 4.25.0
adasiek@mint-desktop:~/python_projekty/simply_black$ ls -la
razem 1480
drwxrwxr-x  4 adasiek adasiek    4096 paź  7 13:27  .
drwxrwxr-x 23 adasiek adasiek    4096 paź  6 18:48  ..
drwxrwxr-x  8 adasiek adasiek    4096 paź  7 13:27  .git
drwxrwxr-x  2 adasiek adasiek    4096 paź  6 18:39  images
-rw-rw-r--  1 adasiek adasiek    1064 paź  6 18:39  LICENSE
-rw-rw-r--  1 adasiek adasiek 1183127 paź  7 13:27  PySimpleGUI_patched.py
-rw-rw-r--  1 adasiek adasiek    3037 paź  6 18:39  README.md
-rw-rw-r--  1 adasiek adasiek     316 paź  7 13:27 'simply_black changelog.txt'
-rw-rw-r--  1 adasiek adasiek  287691 paź  7 13:27  simply_black.embedded.py
-rw-rw-r--  1 adasiek adasiek    9513 paź  7 13:27  simply_black.py
adasiek@mint-desktop:~/python_projekty/simply_black$ 
```

**Comment by salabim** [comment]
The embedded version should work now. Sorry for embedding the wrong version.
